# Generated by Django 4.2.30 on 2026-09-03 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatPayWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=19, unique=True, verbose_name='Número de tarjeta virtual')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo (CLP)')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada por cliente o sistema anti-robo')], default='activa', max_length=20, verbose_name='Estado')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('concepto', models.CharField(blank=True, default='', max_length=120, verbose_name='Comercio/Origen')),
                ('tipo', models.CharField(choices=[('compra_cliente', 'Compra de cliente'), ('pago_proveedor', 'Pago a proveedor'), ('recarga', 'Recarga de saldo')], max_length=30, verbose_name='Tipo de operación')),
                ('resultado', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada_saldo', 'Rechazada por saldo insuficiente'), ('rechazada_fraude', 'Rechazada por fraude'), ('cancelada', 'Cancelada')], default='aprobada', max_length=30, verbose_name='Resultado')),
                ('referencia', models.CharField(blank=True, default='', max_length=60, verbose_name='Referencia orden')),
                ('folio', models.PositiveIntegerField(unique=True, verbose_name='Folio')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.beatpaywallet')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.PositiveIntegerField(verbose_name='Folio único')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('concepto', models.CharField(default='', max_length=120, verbose_name='Concepto')),
                ('resultado', models.CharField(max_length=30, verbose_name='Resultado')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='vouchers/', verbose_name='Comprobante PDF')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='payments.transaction')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
