# Generated by Django 4.2.30 on 2026-09-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bpass_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='BPass protegido'),
        ),
    ]
