# Generated by Django 4.2.30 on 2026-09-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bpass_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moneda',
            field=models.CharField(blank=True, default='CLP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pais',
            field=models.CharField(blank=True, default='CL', max_length=2, verbose_name='País'),
        ),
    ]
