# Generated by Django 4.2.30 on 2026-09-03 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre de la regla')),
                ('umbral_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umbral de monto sospechoso (CLP)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('monto_inusual', 'Monto inusual'), ('intentos_fallidos', 'Múltiples intentos fallidos'), ('bloqueo_preventivo', 'Bloqueo preventivo'), ('tarjeta_reportada', 'Tarjeta reportada/robada')], max_length=30, verbose_name='Tipo de alerta')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto implicado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
